# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e0b8f71eb34aafa3de5db958afec5fc2ec7863d4b8c8ea74704cc185f5729f920182683e0925bfd9bf5d020d4cb1e42c6c938ebd739dac6ea2d800b60df4246

test:
  secret_key_base: 8f5c808fa1c61be726ec2d031bdd30dd663ad496b13145b0068622eaefb2cea66f4ff8c392d722c8bf965bc88cad2969373ada757d9a8261a20f9497875342b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
